name: Shadownaives-Release
run-name: ${{ github.actor }}
on:
  push:
    tags:
      - '*'

jobs:
  Shadownaives-Release:
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build app for release
        run: msbuild shadownaives.sln /t:Clean,Build /p:platform="Any CPU" /p:Configuration=Release

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Package for Windows
        run: |
          cd shadownaives/bin/Release/
          7z a -tzip -mx=9 -mfb=128 ../shadownaives-${{ steps.get_version.outputs.VERSION }}-windows.zip .

      - name: Upload Release Asset 	
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: shadownaives/bin/*.zip
          tag: ${{ github.ref }}
          file_glob: true
          prerelease: true
